import { Button, CheckBox, GroupBox, VerticalBox, ProgressIndicator, ComboBox, LineEdit, HorizontalBox, ScrollView, ListView } from "std-widgets.slint";

import { TreeView } from "treeview.slint";

export struct InkscapeArgs {
    output_dir: string,
    export_png: bool,
    export_pdf: bool,
    export_eps: bool,
}

export component AppUI inherits Window {
    min-width: 400px;
    min-height: 400px;
    in-out property<string> output_dir;
    in-out property<bool> export_png: true;
    in-out property<bool> export_pdf: false;
    in-out property<bool> export_eps: false;
    callback show-folder-dialog();
    callback convert(InkscapeArgs);
    // callback toggle-export-png(bool);
    // callback toggle-export-pdf(bool);
    // callback toggle-export-eps(bool);
    GridLayout {
        spacing: 5px;
        Row {
            TreeView {
                root_directory: "C:\\";
            }
            VerticalLayout {
                GroupBox {
                    title: "Geometry:";
                    VerticalLayout {
                        CheckBox { text: "PNG"; checked: export_png; toggled => { root.export_png = self.checked; } }
                        CheckBox { text: "PDF"; checked: export_pdf; toggled => { root.export_pdf = self.checked; } }
                        CheckBox { text: "EPS"; checked: export_eps; toggled => { root.export_eps = self.checked; } }
                        // CheckBox { text: "PNG"; checked: export_png; toggled => { root.toggle-export-png(self.checked); } }
                        // CheckBox { text: "PDF"; checked: export_pdf; toggled => { root.toggle-export-pdf(self.checked); } }
                        // CheckBox { text: "EPS"; checked: export_eps; toggled => { root.toggle-export-eps(self.checked); } }
                    }
                }
                GroupBox {
                    title: "Export:";
                    VerticalLayout {
                        ComboBox {
                            height: 35px;
                            model: ["Page", "Drawing", "Custom"];
                            current-value: "Page";
                        }
                    }
                }
                HorizontalBox {
                    LineEdit {
                        input-type: text;
                        placeholder-text: "Output directory";
                        text: output_dir;
                    }
                    Button {
                        // icon: @image-url("folder-outline.svg");
                        text: "📂";
                        clicked => {
                            root.show-folder-dialog();
                        }
                    }
                }
            }
        }
        Row {
            Button {
                colspan: 2;
                text: "Convert";
                clicked => {
                    root.convert({
                        output_dir: root.output_dir,
                        export_png: root.export_png,
                        export_pdf: root.export_pdf,
                        export_eps: root.export_eps,
                    })
                }
            }
        }
        Row {
            ProgressIndicator {
                colspan: 2;
                height: 15px;
                progress: 30%;
            }
        }
    }
}
