import { Button, CheckBox, GroupBox, VerticalBox, ProgressIndicator, ComboBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    in-out property<bool> export_png: true;
    in-out property<bool> export_pdf: false;
    in-out property<bool> export_eps: false;
    callback request-increase-value();
    callback toggle-export-png(bool);
    callback toggle-export-pdf(bool);
    callback toggle-export-eps(bool);
    VerticalLayout {
        VerticalBox {
            Text {
                text: "Counter: \{root.counter}";
            }
            Button {
                text: "Increase value";
                clicked => {
                    root.request-increase-value();
                }
            }
        }
        GroupBox {
            title: "Geometry:";
            VerticalLayout {
                CheckBox { text: "PNG"; checked: true; toggled => { root.toggle-export-png(self.checked); } }
                CheckBox { text: "PDF"; checked: false; toggled => { root.toggle-export-pdf(self.checked); } }
                CheckBox { text: "EPS"; checked: false; toggled => { root.toggle-export-eps(self.checked); } }
            }
        }
        GroupBox {
            title: "Export:";
            ComboBox {
                width: parent.width;
                model: ["Page", "Drawing", "Custom"];
                current-value: "Page";
            }
        }
        ProgressIndicator {
            width: parent.width;
            height: 15px;
            progress: 30%;
        }
    }
}
