import { Button, CheckBox, GroupBox, VerticalBox, ProgressIndicator, ComboBox, LineEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<string> output_dir;
    callback show-folder-dialog();
    callback toggle-export-png(bool);
    callback toggle-export-pdf(bool);
    callback toggle-export-eps(bool);
    VerticalLayout {
        GroupBox {
            title: "Geometry:";
            VerticalLayout {
                CheckBox { text: "PNG"; checked: true; toggled => { root.toggle-export-png(self.checked); } }
                CheckBox { text: "PDF"; checked: false; toggled => { root.toggle-export-pdf(self.checked); } }
                CheckBox { text: "EPS"; checked: false; toggled => { root.toggle-export-eps(self.checked); } }
            }
        }
        GroupBox {
            title: "Export:";
            ComboBox {
                width: parent.width;
                model: ["Page", "Drawing", "Custom"];
                current-value: "Page";
            }
        }
        HorizontalBox {
            LineEdit {
                input-type: text;
                placeholder-text: "Output directory";
                text: output_dir;
            }
            Button {
                // icon: @image-url("folder-outline.svg");
                text: "📂";
                clicked => {
                    root.show-folder-dialog();
                }
            }
        }
        ProgressIndicator {
            width: parent.width;
            height: 15px;
            progress: 30%;
        }
    }
}
